# Generated by Django 4.1.6 on 2023-03-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='consult_pending',
        ),
    ]
