# Generated by Django 4.1.6 on 2023-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FireDetectionApp', '0004_remove_userprofile_user_delete_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_no', models.IntegerField()),
                ('instance_intensity', models.CharField(max_length=50)),
                ('instance_time', models.CharField(max_length=50)),
                ('instance_date', models.CharField(max_length=50)),
                ('instance_address', models.CharField(max_length=100)),
            ],
        ),
    ]
